#! /bin/sh

#sxhkd &
#dunst &
#redshift -l 49:8 -t 6500:4600 &
#compton --config ~/.config/compton/compton.conf &

bspc config border_width         6
bspc config window_gap           12

bspc config normal_border_color "#2C3E50"
bspc config active_border_color "#2C3E50"
bspc config focused_border_color "#e0e0e0"

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_by_distance    true
bspc config history_aware_focus  true

bspc monitor DVI-I-1 -d I II
bspc monitor DVI-I-2 -d III IV V

bspc rule -a Chromium desktop=^2
bspc rule -a mplayer2 state=floating
